# Generated by Django 5.2.1 on 2025-08-21 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_earthquake_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='earthquake',
            unique_together={('time', 'latitude', 'longitude', 'depth', 'magnitude')},
        ),
    ]
